import type { GestionCambio, UsuarioGestionCambio } from "./types";

export const usuariosMock: UsuarioGestionCambio[] = [
  {
    id: "u-lider-operaciones",
    nombre: "Mariana Gómez",
    correo: "mariana.gomez@incomineria.com",
    empresa: "Incominería",
    rol: "LIDER_PROCESO",
    proceso: "Operaciones",
    activo: true,
  },
  {
    id: "u-calidad",
    nombre: "Gestión de Calidad",
    correo: "calidad@incomineria.com",
    empresa: "Incominería",
    rol: "GESTION_CALIDAD",
    activo: true,
  },
  {
    id: "u-gerencia",
    nombre: "Gerencia Administrativa",
    correo: "gerencia@incomineria.com",
    empresa: "Incominería",
    rol: "GERENCIA_ADMINISTRATIVA",
    activo: true,
  },
  {
    id: "u-lider-mantenimiento",
    nombre: "Carlos Rincón",
    correo: "carlos.rincon@incomineria.com",
    empresa: "Incominería",
    rol: "LIDER_PROCESO",
    proceso: "Mantenimiento",
    activo: true,
  },
];

export const registrosMock: GestionCambio[] = [
  {
    id: "gc-mock-001",
    codigo: "GC-2026-001",
    fecha: "2026-07-01",
    empresa: "Incominería",
    liderProceso: "Mariana Gómez",
    proceso: "Operaciones",
    tipoCambio: "PROCESOS",
    estado: "EN_REVISION",
    responsableActual: "GESTION_CALIDAD",
    creadorId: "u-lider-operaciones",
    liderProcesoId: "u-lider-operaciones",
    historial: [],
    detalle: {
      empresa: "Incominería",
      liderProceso: "Mariana Gómez",
      proceso: "Operaciones",
      tiposCambio: ["PROCESOS"],
      analisis: {
        documentos: "Actualización del procedimiento operativo.",
        procesos: "Cambio en la secuencia de inspección.",
        personas: "Reentrenamiento al equipo operativo.",
        instalaciones: "",
        "tecnologia-maquinaria": "",
        "riesgos-organizacionales": "Riesgo de reproceso durante la transición.",
        "peligros-riesgos": "Control operativo reforzado.",
        "aspectos-impactos-ambientales": "",
      },
      plan: [
        {
          id: 1,
          actividades: "Socializar el nuevo procedimiento",
          responsable: "Líder de proceso",
          fecha: "2026-07-08",
        },
      ],
    },
  },
  {
    id: "gc-mock-002",
    codigo: "GC-2026-002",
    fecha: "2026-06-27",
    empresa: "Incominería",
    liderProceso: "Carlos Rincón",
    proceso: "Mantenimiento",
    tipoCambio: "TECNOLOGÍA / MAQUINARIA",
    estado: "PENDIENTE_FIRMA",
    responsableActual: "GERENCIA_ADMINISTRATIVA",
    creadorId: "u-lider-mantenimiento",
    liderProcesoId: "u-lider-mantenimiento",
    validacionCalidad: "Cambio validado por Calidad para firma administrativa.",
    historial: [],
    detalle: {
      empresa: "Incominería",
      liderProceso: "Carlos Rincón",
      proceso: "Mantenimiento",
      tiposCambio: ["TECNOLOGÍA / MAQUINARIA"],
      analisis: {
        documentos: "Actualizar ficha técnica.",
        procesos: "Ajuste del plan preventivo.",
        personas: "",
        instalaciones: "",
        "tecnologia-maquinaria": "Incorporación de equipo de soporte.",
        "riesgos-organizacionales": "",
        "peligros-riesgos": "Validar bloqueo y etiquetado.",
        "aspectos-impactos-ambientales": "",
      },
      plan: [],
    },
  },
];
