import type { GestionCambio, UsuarioGestionCambio } from "./types";

export const usuariosMock: UsuarioGestionCambio[] = [
  {
    id: "u-lider-operaciones",
    nombre: "Mariana Gómez",
    correo: "mariana.gomez@incomineria.com",
    empresa: "Incominería",
    rol: "LIDER_PROCESO",
    proceso: "Operaciones",
    activo: true,
  },
  {
    id: "u-calidad",
    nombre: "Gestión de Calidad",
    correo: "calidad@incomineria.com",
    empresa: "Incominería",
    rol: "GESTION_CALIDAD",
    activo: true,
  },
  {
    id: "u-gerencia",
    nombre: "Gerencia Administrativa",
    correo: "gerencia@incomineria.com",
    empresa: "Incominería",
    rol: "GERENCIA_ADMINISTRATIVA",
    activo: true,
  },
  {
    id: "u-lider-mantenimiento",
    nombre: "Carlos Rincón",
    correo: "carlos.rincon@incomineria.com",
    empresa: "Incominería",
    rol: "LIDER_PROCESO",
    proceso: "Mantenimiento",
    activo: true,
  },
  {
    id: "u-jefe-hse",
    nombre: "Laura Pérez",
    correo: "laura.perez@incomineria.com",
    empresa: "Incominería",
    rol: "APROBADOR_ADICIONAL",
    proceso: "Gestión HSE",
    activo: true,
  },
];

export const registrosMock: GestionCambio[] = [
  {
    id: "gc-mock-001",
    codigo: "GC-2026-001",
    fecha: "2026-07-01",
    empresa: "Incominería",
    liderProceso: "Mariana Gómez",
    proceso: "Operaciones",
    tipoCambio: "PROCESOS",
    estado: "EN_REVISION_CALIDAD",
    responsableActual: "GESTION_CALIDAD",
    responsableActualId: "u-calidad",
    responsableActualNombre: "Gestión de Calidad",
    creadorId: "u-lider-operaciones",
    liderProcesoId: "u-lider-operaciones",
    aprobadorSeleccionadoId: "u-gerencia",
    aprobadorSeleccionadoNombre: "Gerencia Administrativa",
    aprobadorSeleccionadoRol: "GERENCIA_ADMINISTRATIVA",
    historial: [
      {
        accion: "REENVIAR_CALIDAD",
        fecha: "2026-07-01T08:00:00.000Z",
        usuario: "Mariana Gómez",
        rol: "LIDER_PROCESO",
        estadoAnterior: "BORRADOR",
        estadoNuevo: "EN_REVISION_CALIDAD",
        observaciones: "Registro creado y enviado a revisión inicial de Calidad.",
      },
    ],
    detalle: {
      empresa: "Incominería",
      liderProceso: "Mariana Gómez",
      liderProcesoId: "u-lider-operaciones",
      proceso: "Operaciones",
      tiposCambio: ["PROCESOS"],
      aprobadorSeleccionadoId: "u-gerencia",
      analisis: {
        documentos: "Actualización del procedimiento operativo.",
        procesos: "Cambio en la secuencia de inspección.",
        personas: "Reentrenamiento al equipo operativo.",
        instalaciones: "",
        "tecnologia-maquinaria": "",
        "riesgos-organizacionales": "Riesgo de reproceso durante la transición.",
        "peligros-riesgos": "Control operativo reforzado.",
        "aspectos-impactos-ambientales": "",
      },
      plan: [
        {
          id: 1,
          actividades: "Socializar el nuevo procedimiento",
          responsable: "Líder de proceso",
          fecha: "2026-07-08",
        },
      ],
    },
  },
  {
    id: "gc-mock-002",
    codigo: "GC-2026-002",
    fecha: "2026-06-27",
    empresa: "Incominería",
    liderProceso: "Carlos Rincón",
    proceso: "Mantenimiento",
    tipoCambio: "TECNOLOGÍA / MAQUINARIA",
    estado: "PENDIENTE_APROBACION",
    responsableActual: "GERENCIA_ADMINISTRATIVA",
    responsableActualId: "u-gerencia",
    responsableActualNombre: "Gerencia Administrativa",
    creadorId: "u-lider-mantenimiento",
    liderProcesoId: "u-lider-mantenimiento",
    aprobadorSeleccionadoId: "u-gerencia",
    aprobadorSeleccionadoNombre: "Gerencia Administrativa",
    aprobadorSeleccionadoRol: "GERENCIA_ADMINISTRATIVA",
    validacionCalidad: "Cambio validado por Calidad para firma administrativa.",
    historial: [
      {
        accion: "VALIDAR_REMITIR",
        fecha: "2026-06-28T09:30:00.000Z",
        usuario: "Gestión de Calidad",
        rol: "GESTION_CALIDAD",
        estadoAnterior: "EN_REVISION_CALIDAD",
        estadoNuevo: "PENDIENTE_APROBACION",
        observaciones: "Cambio validado por Calidad para firma administrativa.",
      },
    ],
    detalle: {
      empresa: "Incominería",
      liderProceso: "Carlos Rincón",
      liderProcesoId: "u-lider-mantenimiento",
      proceso: "Mantenimiento",
      tiposCambio: ["TECNOLOGÍA / MAQUINARIA"],
      aprobadorSeleccionadoId: "u-gerencia",
      analisis: {
        documentos: "Actualizar ficha técnica.",
        procesos: "Ajuste del plan preventivo.",
        personas: "",
        instalaciones: "",
        "tecnologia-maquinaria": "Incorporación de equipo de soporte.",
        "riesgos-organizacionales": "",
        "peligros-riesgos": "Validar bloqueo y etiquetado.",
        "aspectos-impactos-ambientales": "",
      },
      plan: [],
    },
  },
  {
    id: "gc-mock-003",
    codigo: "GC-2026-003",
    fecha: "2026-04-12",
    empresa: "Incominería",
    liderProceso: "Mariana Gómez",
    proceso: "Gestión HSE",
    tipoCambio: "REQUISITOS LEGALES",
    estado: "EN_SEGUIMIENTO_CALIDAD",
    responsableActual: "GESTION_CALIDAD",
    responsableActualId: "u-calidad",
    responsableActualNombre: "Gestión de Calidad",
    creadorId: "u-lider-operaciones",
    liderProcesoId: "u-lider-operaciones",
    aprobadorSeleccionadoId: "u-jefe-hse",
    aprobadorSeleccionadoNombre: "Laura Pérez",
    aprobadorSeleccionadoRol: "APROBADOR_ADICIONAL",
    validacionCalidad: "Documentación completa. Se remite a aprobador HSE.",
    fechaAprobacion: "2026-04-20",
    fechaInicioSeguimiento: "2026-04-20",
    fechaLimiteCierre: "2026-07-20",
    aprobacion: {
      aprobado: "SI",
      nombre: "Laura Pérez",
      cargo: "Jefe HSE",
      fecha: "2026-04-20",
      observaciones: "Aprobado con seguimiento a indicadores legales.",
      rolAprobador: "APROBADOR_ADICIONAL",
    },
    historial: [
      {
        accion: "VALIDAR_REMITIR",
        fecha: "2026-04-18T10:00:00.000Z",
        usuario: "Gestión de Calidad",
        rol: "GESTION_CALIDAD",
        estadoAnterior: "EN_REVISION_CALIDAD",
        estadoNuevo: "PENDIENTE_APROBACION",
        observaciones: "Documentación completa. Se remite a aprobador HSE.",
      },
      {
        accion: "REGISTRAR_APROBACION",
        fecha: "2026-04-20T15:15:00.000Z",
        usuario: "Laura Pérez",
        rol: "APROBADOR_ADICIONAL",
        estadoAnterior: "PENDIENTE_APROBACION",
        estadoNuevo: "EN_SEGUIMIENTO_CALIDAD",
        observaciones: "Aprobado con seguimiento a indicadores legales.",
      },
    ],
    detalle: {
      empresa: "Incominería",
      liderProceso: "Mariana Gómez",
      liderProcesoId: "u-lider-operaciones",
      proceso: "Gestión HSE",
      tiposCambio: ["REQUISITOS LEGALES"],
      aprobadorSeleccionadoId: "u-jefe-hse",
      analisis: {
        documentos: "Actualizar matriz legal y procedimiento HSE.",
        procesos: "Incluir nueva validación mensual.",
        personas: "Socialización al equipo operativo.",
        instalaciones: "",
        "tecnologia-maquinaria": "",
        "riesgos-organizacionales": "Riesgo de incumplimiento si no se ajusta el control.",
        "peligros-riesgos": "Refuerzo en permisos de trabajo.",
        "aspectos-impactos-ambientales": "Validar requisitos ambientales asociados.",
      },
      plan: [
        {
          id: 1,
          actividades: "Actualizar matriz legal",
          responsable: "Gestión HSE",
          fecha: "2026-05-05",
        },
      ],
    },
  },
];
